### ISSUE TITLE
Connect with Codacy

### ISSUE THREAD

**Issue by GlennKintscher** [KatastrophenTeam/StreamingFrog#6]
Add this to .travis.yml file:

```yaml
before_install:
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly

after_success:
  - ~/jpm/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
```
Add this to Travis environment variables:  
`CODACY_PROJECT_TOKEN` = `53b14428a4c948d2a6555bb3423b3f3c`
